#!/bin/bash
python get3Structures.py "Al" "Co" "Ni"
cp -rf Structures/ Structures_AlCoNi/
rm -rf Structures/

python get3Structures.py "Ag" "H" "Pd"
cp -rf Structures/ Structures_AgHPd/
rm -rf Structures/

python get3Structures.py "Mo" "U" "Xe"
cp -rf Structures/ Structures_MoUXe/
rm -rf Structures/

python get3Structures.py "H" "He" "W"
cp -rf Structures/ Structures_HHeW/
rm -rf Structures/

python get3Structures.py "Cr" "Fe" "Ni"
cp -rf Structures/ Structures_CrFeNi/
rm -rf Structures/



